### ISSUE TITLE
Migrations not working

### ISSUE THREAD

**Issue by joshuafcole** [joshuafcole/recall#15] opened 2014-04-21 02:01 UTC

**Comment by joshuafcole** [comment] 2014-04-21 02:08
This only affects protocol 1..2 migrations.

**Comment by joshuafcole** [comment] 2014-04-21 04:04
@seancorfield The most likely issue now is that the state of your file system no longer matches the files to be recalled. I'll need to properly guard against that as a part of the new code which get's the editor for a tab.

**Comment by seancorfield** [comment] 2014-04-21 04:10
Yes, it still matches the files. Previously Recall worked cross-platform so as I moved back and forth between my Mac and my Windows machine - which have the exact same file system structure - the files would be restored as expected each time I opened LT, to the state I closed it on the other machine. I'll try 0.1.5 on my Mac tomorrow, just pointing this out since I tried 0.1.5 on my Windows machine so if it's no longer handling / in file paths correctly, that could be the cause.

**Comment by joshuafcole** [comment] 2014-04-21 04:15
The path handling is all done through LT (I internally trigger the :open-path command), so I hope that's not the case. The issue I expect we're finding  from the stack trace is that 1. I ask to have the file opened, 2. The file is not found / can't be opened. 3. We try to lookup the editor for the tab containing that file (which doesn't exist). This derefs the tab (which is null) and breaks things.

The other possibility is -- ah, that's the issue. If you have plugin or other tabs open which aren't filebacked, you also run into the problem. Regardless, fault tolerance is a good thing so I'll set it up to ensure we have a tab to interact with before trying to interact with it.

Thanks for the report.

**Comment by seancorfield** [comment] 2014-04-21 04:17
One of my tabs is always console... :)

**Comment by joshuafcole** [comment] 2014-04-21 05:04
Updated, should do the trick.

**Closed as completed** 2014-04-21 05:08 UTC
Labels: bug

**Comment by seancorfield** [comment] 2014-04-21 06:09
Yup. That works. Updating the plugin seemed to delete the workspaces folder tho', so I had to restore it from DropBox again. But opening LT after that showed all my tabs and files as expected.

**Comment by joshuafcole** [comment] 2014-04-21 06:12
Interesting. That's probably an artifact of how LT handles plugin updates (I assumed it would just git pull, but I imagine it's instead using tarballs, which makes sense). In that case, in the next feature to work on is tying into LT's workspace system and storing recall files outside of the plugin dir.

**Comment by seancorfield** [comment] 2014-04-21 06:30
Sounds good. Glad I can undelete Dropbox folders for now :)

**Comment by seancorfield** [comment] 2014-04-21 15:30
Verified this morning that the migrated file created on Windows works correctly on Mac too. Thanx.
