### ISSUE TITLE
Should files be persisted when opening Light table?

### ISSUE THREAD

**Issue by jonoabroad** [joshuafcole/recall#11] opened 2014-01-22 01:21 UTC
At the moment I am only get my tabset persisted, but without any files or the console.

Cheers 
Jono

**Comment by joshuafcole** [comment] 2014-01-22 01:24
Sorry, what do you mean by without files? E.g. you mean the tabsets are opened but the file-backed tabs are not? That would definitely be a bug. Currently recall only supports restoring file-backed tabs (considering how to add support for any tab, but no obvious and elegant solutions have occurred to me yet). I do intend to tackle that sooner rather than later though, starting with storing the most recent active tab from each tabset and restoring focus to that, and then restoring other UI state as well (e.g. the console). I'd just like to in general avoid hardcoding support if a more abstract solution can be provided which would also handle 3rd party plugins.

**Comment by jonoabroad** [comment] 2014-01-22 01:35
That is correct, the file-backed tabs are not opening. 
setup
OS X 10.9.1
Light table 0.6.0 Binary 0.8.4
Recall Version 0.0.6

**Comment by joshuafcole** [comment] 2014-01-22 01:44
Interesting, everything seems to be working for me on 10.8. Can you please
post the contents of plugins/Recall/workspaces/default.json ?

On Tue, Jan 21, 2014 at 5:35 PM, Jonathan Ferguson <notifications@github.com

> wrote:
> 
> That is correct, the file-backed tabs are not opening.
> setup
> OS X 10.9.1
> Light table 0.6.0 Binary 0.8.4
> Recall Version 0.0.6
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/recall/issues/11#issuecomment-32985540
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by jonoabroad** [comment] 2014-01-22 01:53
From 
/Users/jonoabroad/Library/Application Support/LightTable/plugins/Recall/workspaces
$ cat default.json 
{"protocol":0,"tabs":[["",""],[""]],"lastActive":""}

**Comment by joshuafcole** [comment] 2014-01-22 01:56
Interesting. So, the last time it was able to save default.json, it saw you
had two tabsets, the first containing two tabs and the last containing one.
Is that accurate? If you delete a tabset and/or change the number of tabs
in one of those tabsets, does default.json update accordingly? (Note that
your workspace is serialized lazily when LT is closed rather than as soon
as a change is made).

On Tue, Jan 21, 2014 at 5:53 PM, Jonathan Ferguson <notifications@github.com

> wrote:
> 
> From
> /Users/jonoabroad/Library/Application
> Support/LightTable/plugins/Recall/workspaces
> $ cat default.json
> {"protocol":0,"tabs":[["",""],[""]],"lastActive":""}
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/recall/issues/11#issuecomment-32986489
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by jonoabroad** [comment] 2014-01-22 02:01
That would be correct. 

The welcome page, the console in one and a file in the other.

Yes altering the workspace and the json file has updated

{"protocol":0,"tabs":[[""],["/path/to/my/file.clj"]],"lastActive":""}

And now when I reopen lighttable, the file is present.  I've just tested with the console open and it is reopening with the file correctly. 

Hmmm unsure what is different, other than I am now watching the json file.

**Comment by joshuafcole** [comment] 2014-01-22 02:18
If you can figure out any other ways to reproduce this, please let me know.
Let's leave the issue open for a while in case it crops up again, and if it
appears to be a fluke after it's consistently worked for you for a week or
two then go ahead and close it.

Sorry for the inconvenience.

Cheers,
Josh

On Tue, Jan 21, 2014 at 6:01 PM, Jonathan Ferguson <notifications@github.com

> wrote:
> 
> That would be correct.
> 
> The welcome page, the console in one and a file in the other.
> 
> Yes altering the workspace and the json file has updated
> 
> {"protocol":0,"tabs":[[""],["/path/to/my/file.clj"]],"lastActive":""}
> 
> And now when I reopen lighttable, the file is present. I've just tested
> with the console open and it is reopening with the file correctly.
> 
> Hmmm unsure what is different, other than I am now watching the json file.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/joshuafcole/recall/issues/11#issuecomment-32986854
> .

## 

Screw the environment. Please print this email immediately. And then burn
it.

**Comment by jonoabroad** [comment] 2014-01-22 03:07
That sounds like a good idea. 

Thanks so much for the help. 

Cheers 
Jono

**Closed as completed** 2014-04-20 05:17 UTC
